### ISSUE TITLE
途中まで素晴らしい

### ISSUE THREAD

**Issue by c0a21090** [maskmassan/ProjExD#4]
https://github.com/maskmassan/ProjExD/blob/219500b574ea896435eea8218af63ab7faf3d2d2/ex01/alphabet.py#L1
最初の方は難しくてあんまり理解できなかったが、しっかり書けていて良い。

**Comment by maskmassan** [comment]
ありがとうございます。最初は関数で対象文字と欠陥した文字を書きました。
